- name: Firewalld | Ensure dependencies installed
  ansible.builtin.package:
    name: firewalld
    state: present
    update_cache: true

- name: Firewalld | Ensure firewalld started and enabled
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Firewalld | Ensure iptables-legacy not present
  ansible.builtin.package:
    name: iptables-legacy
    state: absent
    update_cache: true

- name: Firewalld | Remove ssh service when ssh_port != 22
  ansible.posix.firewalld:
    service: ssh
    state: disabled
    immediate: true
    permanent: true
  when: ansible_port != '22'

- name: Firewalld | Add ssh_port to firewalld config
  ansible.posix.firewalld:
    port: "{{ ansible_port }}/tcp"
    immediate: true
    permanent: true
    state: enabled
  when: ansible_port != '22'

- name: Firewalld | Add http service to firewalld config
  ansible.posix.firewalld:
    service: https
    state: enabled
    immediate: true
    permanent: true
  when: f0rt_firewalld_http_enabled
